### ISSUE TITLE
Can't install with full-install (gamma-launcher full-install --anomaly ./Anomaly --gamma ./GAMMA)

### ISSUE THREAD

**Issue by Red007Master** [Mord3rca/gamma-launcher#184] opened 2024-12-07 19:35 UTC
**Arch, AUR package.**

**Command:**
`gamma-launcher full-install --anomaly ./Anomaly --gamma ./GAMMA`

**Error:**
```
[+] Installing mod: Alternative Pseudogiants
Extracting GAMMA/downloads/Alternative_Pseudogiants.7z
    Installing 01 Meshes -> GAMMA/mods/414- Alternative Pseudogiants - KynesPeace
    Installing 02 2k Textures -> GAMMA/mods/414- Alternative Pseudogiants - KynesPeace
Calculating hash of Catspaw_Milspec_PDA-1.14.1.zip: 100%|########################| 768k/768k [00:00<00:00, 294MiB/s]
[+] Installing mod: Milspec PDA
Extracting GAMMA/downloads/Catspaw_Milspec_PDA-1.14.1.zip
Traceback (most recent call last):
  File "/usr/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/launcher/cli.py", line 113, in main
    args.cobject().run(args)
  File "/usr/lib/python3.12/site-packages/launcher/commands/install.py", line 304, in run
    self._install_mods()
  File "/usr/lib/python3.12/site-packages/launcher/commands/install.py", line 253, in _install_mods
    mod.install(self._mod_dir)
  File "/usr/lib/python3.12/site-packages/launcher/mods/installer/default.py", line 68, in install
    with DefaultTempDir(self, prefix="gamma-launcher-modinstall-") as pdir:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/launcher/mods/tempfile.py", line 49, in __enter__
    getattr(self, hotfix)(s)
  File "/usr/lib/python3.12/site-packages/launcher/mods/tempfile.py", line 32, in _post_decompression_hotfix_00_malformed_archive
    p.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/tmp/gamma-launcher-modinstall-um0eqw61/00. Milspec PDA with Kill Tracker (required)/gamedata'
```

What is interesting directory  `/tmp/gamma-launcher-modinstall-um0eqw61` do not exist at all.

This problem is not isolated to my machine only but present on another one (on my friend's setup too).

**Comment by Mord3rca** [comment] 2024-12-07 19:40
Duplicate of #176 , use master version via pip

**Closed by Mord3rca** 2024-12-07 19:40 UTC
Labels: duplicate
