### ISSUE TITLE
Failure to install the mod "Gunslinger Guns for Anomaly"

### ISSUE THREAD

**Issue by complover116** [Mord3rca/gamma-launcher#107] opened 2024-04-04 06:28 UTC
When running `full-install` it prints an error message when installing the "Gunslinger Guns for Anomaly" mod. All other mods appear to install correctly with no error messages. Here's a snippet containing the error message:

```
<.....>
[+] Installing G.A.M.M.A. Large Files v2
  - Using cached gamma_large_files_v2-main.zip
  --> Installing 273- Longreed's fixed artefacts spawns under maps - Longreed
  --> Installing 272- Grulag's Dead Bushes - Grulag
  --> Installing G.A.M.M.A. Large Files
  --> Installing Boomsticks and Sharpsticks 2022 Guns
  --> Installing 312- Gunslinger Guns for Anomaly - Teivazcz & Gunslinger Team
  /!\ Failed to install, directory not found /!\
  --> Installing Burn's Optimised World Models
<.....>
```

Despite the message, it appears that the mod count in Mod Organizer is correct, 444 at the time of writing. The game crashes when trying to start a new game, but I am unfamiliar with how the mods work and can't tell if this is related to a missing mod or not. 

```can't find variable class in wpn_amb17```

.

Thank you for making this!

**Comment by Langolyers** [comment] 2024-04-04 08:26
I get the same `variable class` error, also have all mods showing correctly in the MO. I was able to get into the game by loading an Anomaly save, but then it crashes with the same error afterwards by interacting with pretty much anything.

Digging around the GAMMA Discord, there are people with similar errors and they're recommendation is always to install with the latest version of the GAMMA launcher they provided - which is clearly not an option here. 

I kind of gave up on this for now, but if anyone has a fix, that would be appreciated.

**Comment by Mord3rca** [comment] 2024-04-04 08:39
@complover116 Hi, for Gunslinger mod, this is my bad. I've assumed everything will be in Gamma Large File git but it's not ! I'll wake a fix for this

@complover116  @Langolyers This variable class error was already reported on #96 , however I cannot reproduce it so .... Can't fix it.

**Comment by Langolyers** [comment] 2024-04-04 08:51
Yeah, fair enough, wasn't expecting you to. 😄 

I'd say we can close this and we can move the discussion to the other issue. Apologies for missing that one.

**Comment by Mord3rca** [comment] 2024-04-04 08:52
I'll close this when I have a fix for Gunslinger mod

**Comment by Mord3rca** [comment] 2024-04-07 17:36
@Langolyers Fix done, can you give it a shot ? Thanks !

**Comment by Mord3rca** [comment] 2024-04-18 17:36
No user feedback from 2 weeks.

Merging & Closing

**Closed** 2024-04-18 17:35 UTC
