### ISSUE TITLE
Only downloads 442/446 mods even with build from source

### ISSUE THREAD

**Issue by riku8405** [Mord3rca/gamma-launcher#96] opened 2024-01-20 01:05 UTC
I only download 442 mods even with build from source, and I get this error if I try and run the game
![image](https://github.com/Mord3rca/gamma-launcher/assets/70416702/9eef3fda-11a3-4bb9-be29-2023b3f73759)

**Comment by ToRRent1812** [comment] 2024-02-07 17:40
Similar issue, it shows 442 active everytime I full-install

**Comment by Arherion** [comment] 2024-03-24 15:15
Same issue, new prefix, fresh install.

**Comment by Mord3rca** [comment] 2024-03-24 16:08
@Arherion Regarding the number of mods ? A Fatal Error ? If so, can you screen it please ?

**Comment by Arherion** [comment] 2024-03-24 18:00
@Mord3rca Of course. Game crushes on save loading or starting new game:
![Screenshot_20240324_195631](https://github.com/Mord3rca/gamma-launcher/assets/2121755/5c1842eb-71fc-44cb-9c04-80f182043b33)
Error is the same all the time, so it's not something floating.


Regarding mod number is 444, with 1 marked as not valid:
![Screenshot_20240324_195147](https://github.com/Mord3rca/gamma-launcher/assets/2121755/8bab1d2d-1533-4632-a388-ecb19a48fbdc)

Previously had gamma working fine.
If there anything I can test, just point me what to do

**Comment by Mord3rca** [comment] 2024-03-24 18:12
For High Res PDA, this is a definition error see #98 

Just reinstalled my game and I cannot reproduce your error regarding wpn-amb17. On which map do you start ? Faction ? Loadout ? ....

**Comment by Arherion** [comment] 2024-03-26 20:42
Ok, noted on High Res PDA matter.

Any map, any faction, any loadout.
Multiple versions of wine (9.5, lutris-7.2, wine-ge-8.26), same result.
Previously, run smoothly.

**Comment by Langolyers** [comment] 2024-04-04 08:53
Same here. It is a GAMMA thing. Anomaly runs fine under the same conditions, and browsing through the GAMMA Discord a there's a few people having similar errors running on Windows. 

Unfortunately the fix they suggest is to make sure you're using the latest version of their launcher, which doesn't help us on Linux.

**Comment by Langolyers** [comment] 2024-04-05 17:26
I can't reproduce the error on Windows here. Is a meld between the Windows and Linux folders of any use?

**Comment by Mord3rca** [comment] 2024-04-05 19:03
Nope, there will be a lot of differences which wont be the cause of the issue

**Comment by Langolyers** [comment] 2024-04-20 15:48
Was able to get it working using the modded exes for Anomaly. You need to disable mod 166 however, otherwise it generates another crash when you open the inventory.

**Comment by Mord3rca** [comment] 2024-04-26 19:19
#110 have a fix for mod 164

However, I still don't understand the wpn_amb17 error ... It happen sometimes but on save reload, the error just disappear.

**Comment by Mord3rca** [comment] 2024-05-01 18:44
@Arherion #115 should resolve the wpn_amb17 error, just tested on my side.

**Closed** 2024-05-04 05:26 UTC
