### ISSUE TITLE
Gamma download fails

### ISSUE THREAD

**Issue by MichaelHochriegl** [Mord3rca/gamma-launcher#185] opened 2024-12-11 19:04 UTC
Sorry for opening another issue, but I wanted to get a clean base to check with `meld` why I'm not able to start Gamma.
So I deleted everything and started from scratch again, only problem now:

I can download and start Anomaly just fine, but when I do the full-install for Gamma I always get this error:
```
 gamma-launcher full-install --anomaly /home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/Anomaly --gamma /home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/GAMMA
[+] Installing base setup for GAMMA
  - Downloading modorganizer-Mod.Organizer-2.4.4.7z: 85.9MiB [00:11, 8.04MiB/s]
Extracting /tmp/gamma-launcher-mo-setup-fqf6onbu/modorganizer-Mod.Organizer-2.4.4.7z
    Fetching remote Grokitach from gamma_setup.git...
[+] Updating G.A.M.M.A. definition
    downloading archive...
    Fetching remote Grokitach from Stalker_GAMMA.git...
Traceback (most recent call last):
  File "/home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/gamma-launcher/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/gamma-launcher/env/lib64/python3.13/site-packages/launcher/cli.py", line 113, in main
    args.cobject().run(args)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/gamma-launcher/env/lib64/python3.13/site-packages/launcher/commands/install.py", line 300, in run
    (self._update_gamma_definition if not args.custom_def else self._set_custom_gamma_def)(args.custom_def)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/gamma-launcher/env/lib64/python3.13/site-packages/launcher/commands/install.py", line 215, in _update_gamma_definition
    g.download(self._dl_dir, use_cached=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/gamma-launcher/env/lib64/python3.13/site-packages/launcher/mods/downloader/github/git.py", line 27, in download
    remote.fetch()
    ~~~~~~~~~~~~^^
  File "/home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/gamma-launcher/env/lib64/python3.13/site-packages/git/remote.py", line 1069, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
  File "/home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/gamma-launcher/env/lib64/python3.13/site-packages/git/remote.py", line 895, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/drcox1911/.var/app/com.usebottles.bottles/data/bottles/bottles/Gamma/drive_c/gamma-launcher/env/lib64/python3.13/site-packages/git/cmd.py", line 834, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v -- Grokitach
  stderr: 'error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 622 bytes of body are still expected
fatal: early EOF
fatal: fetch-pack: invalid index-pack output'

```

I tried also with a VPN to maybe mitigate any IP block I might have got (was downloading Gamma the last couple of days kinda once daily), but that was of no help.

**Comment by jimmon89** [comment] 2024-12-11 20:07
Just keep trying.
that seems to happen when your PC or ISP drops a packet, as well as other similar situations.
My ISP is pretty terrible, so that has been happening to me a lot since I started downloading.
But whenever it times out on one of the git downloads, it continues where it left off when you start it back up AFAICT.
The huge non-git files have been a major PITA for me, though.
Hopefully we can get a feature to auto-resume downloads that timed out and continue instead of throwing an error and stopping.

**Comment by Mord3rca** [comment] 2024-12-11 20:29
Duplicate of #161, there is nothing I can do if git is failing.
Set **GAMMA_LAUNCHER_NO_GIT=1** env variable to switch to legacy download method if the issue wont go away.

**Closed by Mord3rca** 2024-12-11 20:29 UTC
Labels: duplicate
