### ISSUE TITLE
How to update when fixes are released?

### ISSUE THREAD

**Issue by DoomPenguin9** [Mord3rca/gamma-launcher#63] opened 2023-10-04 18:18 UTC
There is no "update argument" and re-running "full-install" does not install the latest fix for pistol animations. How do I update correctly using this launcher?

**Comment by Mord3rca** [comment] 2023-10-04 18:33
Since #60, updates are automatic. Use master branch to enable the feature.

**Comment by Mord3rca** [comment] 2023-10-05 05:58
Duplicate of #61

**Closed** 2023-10-06 18:24 UTC
Labels: duplicate
