### ISSUE TITLE
Installation bug (file conflict) 

### ISSUE THREAD

**Issue by Red007Master** [Mord3rca/gamma-launcher#189] opened 2024-12-15 20:16 UTC
When installed with `gamma-launcher full-install --anomaly ./Anomaly --gamma ./GAMMA` game won't start because of file conflict

```
file with section "w_sig550.ltx",
file with duplicate "mod_system_zzzzz_3ds_gamma_rifles.ltx"
```

Deleting `w_sig550.ltx` (from 312 Gunslinger for Anomaly) make game start, but there will be crash when you use some scopes.
Or you can modify them.
But replacing the entire folder (312 Gunslinger for Anomaly) with one installed on Windows fix everything.

+ there are some strange behavior of fullscreen, it's better to use borderless as default as Anomaly do.

**Comment by Mord3rca** [comment] 2024-12-15 20:23
Hello, can you provide a diff of the 2 mods folder ?

**Comment by Mord3rca** [comment] 2024-12-15 20:24
Relate to #183

**Comment by Red007Master** [comment] 2024-12-15 23:18
> Hello, can you provide a diff of the 2 mods folder ?

[Uploading diff.txt…](general mod/* diff)

[Uploading diffgunslinga.txt…](diff for _**312- Gunslinger Guns for Anomaly - Teivazcz & Gunslinger Team**_)

**CleanGAMMA** is folder with GAMMA installed with **gamma-launcher** like 1 hour ago.

And other one is installed on Windows (with Grokitach's installer) (+-6 hours ago)

**Comment by Red007Master** [comment] 2024-12-19 00:54
I just tried clean install (but i did not delete cache (if it matters)) and everythin work good (exept window mode (need to set to borderless from fullscreen, if i don't to it GAMMA crash with fattal error on startup)).

**Comment by Mord3rca** [comment] 2024-12-19 07:26
I don't understand how this fixed itself ...

I was pretty sure it was a definition issue GAMMA side but I can't point to which PR on Stalker_GAMMA definition repo fixed this :/

**Comment by Red007Master** [comment] 2024-12-19 10:28
Were you able to understand what the problem was? It was pulling wrong commit? It was pulling files from different commits?

**Comment by MichaelHochriegl** [comment] 2024-12-19 15:18
To me the new Gamma release seems like the most random thing. I'm able to start it one day, but when I try to start the exact same install the next day I get different errors.

**Comment by Mord3rca** [comment] 2024-12-23 16:08
Duplicate of #183

**Comment by Mord3rca** [comment] 2024-12-25 09:53
Continuing discussion on #183

**Closed by Mord3rca** 2024-12-25 09:53 UTC
Labels: duplicate
