### ISSUE TITLE
(CachyOs) Error during installation

### ISSUE THREAD

**Issue by devaszi** [Mord3rca/gamma-launcher#169] opened 2024-11-17 18:40 UTC
hello,
i have been looking if someone had same issue as me and i didnt found anything, so during installation after arround 25 min this crashes the process
  
 Installing Tactical Torch Reanimation -> /home/marcin/Games/stalker/gamma/mods/322- Tactical Torch Reanimation - Skywhyz
Traceback (most recent call last):
  File "/usr/bin/gamma-launcher", line 33, in <module>
    sys.exit(load_entry_point('gamma-launcher==2.0', 'console_scripts', 'gamma-launcher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/launcher/cli.py", line 113, in main
    args.cobject().run(args)
  File "/usr/lib/python3.12/site-packages/launcher/commands/install.py", line 306, in run
    self._install_mods()
  File "/usr/lib/python3.12/site-packages/launcher/commands/install.py", line 254, in _install_mods
    mod.download(self._dl_dir, use_cached=True)
  File "/usr/lib/python3.12/site-packages/launcher/mods/downloader/moddb.py", line 97, in download
    self._url = self._get_download_url(self._url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/launcher/mods/downloader/moddb.py", line 51, in _get_download_url
    return g_session.get(f"https://www.moddb.com{s[0]}", allow_redirects=False).headers["location"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'location'

**Comment by Mord3rca** [comment] 2024-11-17 18:47
Hello,

Duplicate of #167 (probably same issue)

**Comment by Mord3rca** [comment] 2024-11-20 18:07
@devaszi #170 should fix the issue. Can you give it a shot ?

**Comment by devaszi** [comment] 2024-11-20 20:42
i forgot to mention, sorry for that in advance, it actually worked, i just had to launch install few times untill it downloaded all mods, somewhat bruteforced it, but i am not planning to check that again right now (stalker premiere)

**Comment by Mord3rca** [comment] 2024-11-20 20:59
Sometimes bruteforce is the way to go ! Looks resolved then.
Have fun o/

**Closed by Mord3rca** 2024-11-20 20:59 UTC
Labels: duplicate
